spring:
    data:
        cassandra:
            keyspace-name: main
            username: mUUxkXSqLZlOWWWmppHaPKwi
            password: 1yf-cA62Nbsv--fBX7gkkyWABqzOPd_9+ueKWTl-9Cdle8W8Wh2ifwBA.joPKd528rKttOOMUl37eiMSAqa5isfM-CLPzAwxcfDTpe18mqxOSqaq7kCOztIn8,WO6IuK
            schema-action: create-if-not-exists
            request:
                timeout: 10s
            connection:
                connect-timeout: 10s
                init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: 0c411dfc-9a52-4843-87e3-5f23a17a34f6
    region: asia-south1
    keyspace: main
    application.token: AstraCS:mUUxkXSqLZlOWWWmppHaPKwi:a8ddc481ab3ab4a508b28eb5627e91a825560d5cda375aecb9bf5ba5bc715338
